name: Run tests

on: [push]

jobs:
  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.18
        cache: pip # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install pip==24.0
        pip install -r requirements.txt
    - name: Run tests
      run: make test

